name: java-hello-world-maven
'on':
  push:
    paths:
      - java-hello-world-maven/**
      - .github/workflows/java-hello-world-maven.yml
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch: null
permissions:
  contents: read
jobs:
  run:
    name: Run 'java-hello-world-maven'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21.0.2
          distribution: graalvm
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          cache: maven
          native-image-job-reports: 'true'
      - name: Run 'java-hello-world-maven'
        run: |
          cd java-hello-world-maven
          mvn --no-transfer-progress clean package
          java -jar target/my-app-1.0-SNAPSHOT.jar
          mvn --no-transfer-progress clean -Pnative -DskipTests package
          ./target/my-app
